"""
RAG Answer Verification Module

Checks whether a generated answer is actually supported
by the retrieved document context.

Returns only:

SUPPORTED
NOT_SUPPORTED
"""

import os
import re

from dotenv import load_dotenv
from groq import Groq


# ============================================================
# LOAD ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# GROQ CLIENT
# ============================================================

api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise ValueError(
        "GROQ_API_KEY not found in .env file"
    )


llm = Groq(
    api_key=api_key
)


# ============================================================
# CONFIGURATION
# ============================================================

MODEL_NAME = "openai/gpt-oss-20b"

MIN_ANSWER_LENGTH = 10


# ============================================================
# UNKNOWN ANSWER DETECTION
# ============================================================

def is_unknown_answer(answer: str) -> bool:
    """
    Detect answers where the model explicitly says
    that the information is not available.
    """

    if not answer:
        return True

    text = answer.strip().lower()

    unknown_phrases = [
        "i don't know based on the provided documents",
        "i don't know based on the provided document",
        "i do not know based on the provided documents",
        "i do not know based on the provided document",
        "not found in the provided documents",
        "not found in the provided document",
        "cannot be determined from the provided documents",
        "cannot be determined from the provided document",
        "insufficient information in the provided documents",
        "insufficient information in the provided document",
        "not available in the provided documents",
        "not available in the provided document",
    ]

    for phrase in unknown_phrases:

        if phrase in text:
            return True

    return False


# ============================================================
# CLEAN VERIFIER OUTPUT
# ============================================================

def _clean_verifier_result(result: str) -> str:
    """
    Convert the LLM verifier response into exactly
    SUPPORTED or NOT_SUPPORTED.
    """

    if not result:
        return "NOT_SUPPORTED"

    text = result.strip().upper()

    # Remove markdown formatting
    text = text.replace("`", "")

    # Check NOT_SUPPORTED FIRST
    if "NOT_SUPPORTED" in text:
        return "NOT_SUPPORTED"

    if "SUPPORTED" in text:
        return "SUPPORTED"

    return "NOT_SUPPORTED"


# ============================================================
# VERIFY ANSWER
# ============================================================

def verify_answer(
    question: str,
    answer: str,
    context: str,
) -> str:
    """
    Verify whether the generated answer is supported
    by the retrieved document context.

    Parameters
    ----------
    question:
        Original user question.

    answer:
        Answer generated by the RAG LLM.

    context:
        Retrieved and reranked document context.

    Returns
    -------
    str
        SUPPORTED or NOT_SUPPORTED
    """

    # --------------------------------------------------------
    # BASIC VALIDATION
    # --------------------------------------------------------

    if not question or not question.strip():

        return "NOT_SUPPORTED"

    if not answer or not answer.strip():

        return "NOT_SUPPORTED"

    if not context or not context.strip():

        return "NOT_SUPPORTED"

    # --------------------------------------------------------
    # UNKNOWN ANSWER
    # --------------------------------------------------------

    if is_unknown_answer(answer):

        return "NOT_SUPPORTED"

    # --------------------------------------------------------
    # VERY SHORT ANSWER
    # --------------------------------------------------------

    if len(answer.strip()) < MIN_ANSWER_LENGTH:

        return "NOT_SUPPORTED"

    # ========================================================
    # VERIFICATION PROMPT
    # ========================================================

    prompt = f"""
You are a strict document-grounded RAG answer verifier.

Your job is to determine whether the ANSWER is
supported by the DOCUMENT CONTEXT and directly
answers the QUESTION.

IMPORTANT RULES:

1. Use ONLY the DOCUMENT CONTEXT.
2. Do NOT use outside knowledge.
3. Do NOT rely on what you already know.
4. Paraphrasing is allowed.
5. The answer does not need to exactly copy the document.
6. Every important factual claim in the answer must
   be supported by the document context.
7. If the context contains enough evidence to support
   the answer, classify it as SUPPORTED.
8. If the context does not contain enough evidence,
   classify it as NOT_SUPPORTED.
9. If even one important factual claim is unsupported,
   classify it as NOT_SUPPORTED.
10. The answer must actually answer the question.
11. Do not judge whether the answer is generally true.
12. Judge ONLY whether it is supported by the supplied
    document context.

QUESTION:
{question}

DOCUMENT CONTEXT:
{context}

ANSWER:
{answer}

Return exactly ONE of:

SUPPORTED

or

NOT_SUPPORTED

Return nothing else.
"""

    # ========================================================
    # CALL LLM
    # ========================================================

    try:

        response = llm.chat.completions.create(

            model=MODEL_NAME,

            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a strict "
                        "document-evidence verifier. "
                        "Never use outside knowledge."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],

            temperature=0,
        )

        raw_result = (
            response
            .choices[0]
            .message
            .content
            .strip()
        )

        result = _clean_verifier_result(
            raw_result
        )

        print(
            "Verifier result:",
            result
        )

        return result

    except Exception as error:

        print(
            "Answer verification error:",
            error
        )

        return "NOT_SUPPORTED"


# ============================================================
# OPTIONAL EVIDENCE CHECK
# ============================================================

def check_answer_evidence(
    answer: str,
    context: str,
) -> dict:
    """
    Optional helper for debugging.

    This does NOT replace verify_answer().
    It provides simple keyword-overlap information.
    """

    if not answer or not context:

        return {
            "answer_words": 0,
            "context_words": 0,
            "overlap_words": 0,
            "overlap_ratio": 0.0,
        }

    answer_words = set(
        re.findall(
            r"\b[a-zA-Z]{3,}\b",
            answer.lower(),
        )
    )

    context_words = set(
        re.findall(
            r"\b[a-zA-Z]{3,}\b",
            context.lower(),
        )
    )

    overlap = (
        answer_words
        & context_words
    )

    ratio = 0.0

    if answer_words:

        ratio = (
            len(overlap)
            / len(answer_words)
        )

    return {
        "answer_words": len(
            answer_words
        ),
        "context_words": len(
            context_words
        ),
        "overlap_words": len(
            overlap
        ),
        "overlap_ratio": round(
            ratio,
            3
        ),
    }


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    test_question = (
        "What is Generative AI?"
    )

    test_context = """
    Generative AI is a type of artificial
    intelligence that can create new content
    such as text, images, audio and code.
    """

    test_answer = """
    Generative AI is an artificial intelligence
    technology that can create new content such
    as text, images, audio and code.
    """

    result = verify_answer(
        test_question,
        test_answer,
        test_context,
    )

    print(
        "\nVerification:",
        result
    )